using System.Text;

namespace TTMG.Scripting
{
    public static class LuaApiDocsGenerator
    {
        public static string Generate(LuaCommandRegistry? registry = null)
        {
            registry ??= LuaCommandRegistry.Default;
            var commands = registry.Commands;

            var sb = new StringBuilder();
            sb.AppendLine("<!--");
            sb.AppendLine("  This file is generated by `ttmg --emit-lua-docs` from the Lua command registry.");
            sb.AppendLine("  Do not edit by hand; it is regenerated after every build.");
            sb.AppendLine("-->");
            sb.AppendLine();
            sb.AppendLine("# TTMG Lua API");
            sb.AppendLine();
            sb.AppendLine("TTMG runs Lua scripts with a small set of host commands. The canonical way to call");
            sb.AppendLine("them is through the `ttmg` table:");
            sb.AppendLine();
            sb.AppendLine("```lua");
            sb.AppendLine("local name = ttmg.prompt_input(\"Enter your callsign:\", \"Maverick\")");
            sb.AppendLine("ttmg.print(\"Hello, \" .. name)");
            sb.AppendLine("```");
            sb.AppendLine();
            sb.AppendLine("For backwards compatibility every command is *also* registered as a flat global, so");
            sb.AppendLine("existing scripts that call `prompt_input(...)`, `print(...)`, and so on keep working");
            sb.AppendLine("unchanged. Both names resolve to the same function.");
            sb.AppendLine();
            sb.AppendLine("The legacy global names are: " +
                          string.Join(", ", commands.Select(c => $"`{c.Name}`")) + ".");
            sb.AppendLine();
            sb.AppendLine("## Commands");
            sb.AppendLine();

            foreach (var command in commands)
            {
                sb.AppendLine($"### `ttmg.{command.Signature}`");
                sb.AppendLine();
                sb.AppendLine(command.Help);
                sb.AppendLine();

                if (command.Parameters.Count > 0)
                {
                    sb.AppendLine("**Parameters**");
                    sb.AppendLine();
                    foreach (var parameter in command.Parameters)
                    {
                        sb.AppendLine($"- {parameter}");
                    }

                    sb.AppendLine();
                }

                if (!string.IsNullOrWhiteSpace(command.Example))
                {
                    sb.AppendLine("**Example**");
                    sb.AppendLine();
                    sb.AppendLine("```lua");
                    sb.AppendLine(command.Example);
                    sb.AppendLine("```");
                    sb.AppendLine();
                }

                if (command.AnalyzesSecret)
                {
                    sb.AppendLine("> Requires access to the encrypted secret store. TTMG asks for the store");
                    sb.AppendLine("> password once before running the script.");
                    sb.AppendLine();
                }
            }

            return sb.ToString().Replace("\r\n", "\n");
        }

        public static void WriteToFile(string path)
        {
            var fullPath = Path.GetFullPath(path);
            var directory = Path.GetDirectoryName(fullPath);
            if (!string.IsNullOrEmpty(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(fullPath, Generate(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }
    }
}
